export const OPCODE_NOOP = -1
export const OPCODE_HEARTBEAT = 1
export const OPCODE_TELEMETRY = 5
export const OPCODE_HANDSHAKE = 6
export const OPCODE_LOGIN = 19
export const OPCODE_USER_INFO = 32
export const OPCODE_INCOMING_MESSAGE = 128
export const OPCODE_CHAT_UPDATE = 130
export const OPCODE_AUTH = 288
export const OPCODE_AUTH_STATUS = 289
export const OPCODE_AUTH_TRY = 291
export const OPCODE_CLIENT_INFO = 292

export const allOpcodes = [
  OPCODE_NOOP,
  OPCODE_HEARTBEAT,
  OPCODE_TELEMETRY,
  OPCODE_HANDSHAKE,
  OPCODE_LOGIN,
  OPCODE_USER_INFO,
  OPCODE_INCOMING_MESSAGE,
  OPCODE_CHAT_UPDATE,
  OPCODE_AUTH,
  OPCODE_AUTH_STATUS,
  OPCODE_AUTH_TRY,
  OPCODE_CLIENT_INFO,
] as const
